# Generated by Django 3.0.3 on 2020-03-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=None, upload_to='', verbose_name='图片'),
        ),
    ]
