# Generated by Django 3.0.3 on 2020-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=None, upload_to='', verbose_name='图片'),
        ),
    ]
